**Подготовка данных.**

    Создадим исходные таблицы из условия: таблицу сотрудников, таблицу
    клиентов и таблицу клиентов с пропущенными значениями.

In [45]:
from pathlib import Path
from IPython.display import display

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

DATA_DIR = Path("practice_data")
DATA_DIR.mkdir(exist_ok=True)

EMPLOYEE_RECORDS = [
    {
        "ID": 1,
        "Имя": "Иван",
        "Возраст": 25,
        "Должность": "Инженер",
        "Отдел": "IT",
        "Зарплата": 60000,
        "Стаж работы": 2,
    },
    {
        "ID": 2,
        "Имя": "Ольга",
        "Возраст": 30,
        "Должность": "Аналитик",
        "Отдел": "Маркетинг",
        "Зарплата": 75000,
        "Стаж работы": 5,
    },
    {
        "ID": 3,
        "Имя": "Алексей",
        "Возраст": 40,
        "Должность": "Менеджер",
        "Отдел": "Продажи",
        "Зарплата": 90000,
        "Стаж работы": 15,
    },
    {
        "ID": 4,
        "Имя": "Мария",
        "Возраст": 35,
        "Должность": "Программист",
        "Отдел": "IT",
        "Зарплата": 80000,
        "Стаж работы": 7,
    },
    {
        "ID": 5,
        "Имя": "Сергей",
        "Возраст": 28,
        "Должность": "Специалист",
        "Отдел": "HR",
        "Зарплата": 50000,
        "Стаж работы": 3,
    },
    {
        "ID": 6,
        "Имя": "Анна",
        "Возраст": 32,
        "Должность": "Разработчик",
        "Отдел": "IT",
        "Зарплата": 85000,
        "Стаж работы": 6,
    },
    {
        "ID": 7,
        "Имя": "Дмитрий",
        "Возраст": 45,
        "Должность": "HR",
        "Отдел": "HR",
        "Зарплата": 48000,
        "Стаж работы": 12,
    },
    {
        "ID": 8,
        "Имя": "Елена",
        "Возраст": 29,
        "Должность": "Маркетолог",
        "Отдел": "Маркетинг",
        "Зарплата": 70000,
        "Стаж работы": 4,
    },
    {
        "ID": 9,
        "Имя": "Виктор",
        "Возраст": 31,
        "Должность": "Юрист",
        "Отдел": "Юридический",
        "Зарплата": 95000,
        "Стаж работы": 10,
    },
    {
        "ID": 10,
        "Имя": "Алиса",
        "Возраст": 27,
        "Должность": "Дизайнер",
        "Отдел": "Дизайн",
        "Зарплата": 62000,
        "Стаж работы": 5,
    },
    {
        "ID": 11,
        "Имя": "Павел",
        "Возраст": 33,
        "Должность": "Администратор",
        "Отдел": "Администрация",
        "Зарплата": 55000,
        "Стаж работы": 7,
    },
    {
        "ID": 12,
        "Имя": "Светлана",
        "Возраст": 26,
        "Должность": "Тестировщик",
        "Отдел": "Тестирование",
        "Зарплата": 67000,
        "Стаж работы": 2,
    },
    {
        "ID": 13,
        "Имя": "Роман",
        "Возраст": 42,
        "Должность": "Финансист",
        "Отдел": "Финансы",
        "Зарплата": 105000,
        "Стаж работы": 20,
    },
    {
        "ID": 14,
        "Имя": "Татьяна",
        "Возраст": 37,
        "Должность": "Редактор",
        "Отдел": "Редакция",
        "Зарплата": 72000,
        "Стаж работы": 9,
    },
    {
        "ID": 15,
        "Имя": "Николай",
        "Возраст": 39,
        "Должность": "Логист",
        "Отдел": "Логистика",
        "Зарплата": 75000,
        "Стаж работы": 11,
    },
    {
        "ID": 16,
        "Имя": "Валерия",
        "Возраст": 24,
        "Должность": "SEO-специалист",
        "Отдел": "SEO",
        "Зарплата": 64000,
        "Стаж работы": 3,
    },
    {
        "ID": 17,
        "Имя": "Григорий",
        "Возраст": 50,
        "Должность": "Бухгалтер",
        "Отдел": "Бухгалтерия",
        "Зарплата": 110000,
        "Стаж работы": 25,
    },
    {
        "ID": 18,
        "Имя": "Юлия",
        "Возраст": 45,
        "Должность": "Директор",
        "Отдел": "Финансы",
        "Зарплата": 150000,
        "Стаж работы": 20,
    },
    {
        "ID": 19,
        "Имя": "Степан",
        "Возраст": 41,
        "Должность": "Экономист",
        "Отдел": "Экономика",
        "Зарплата": 98000,
        "Стаж работы": 14,
    },
    {
        "ID": 20,
        "Имя": "Василиса",
        "Возраст": 38,
        "Должность": "Проект-менеджер",
        "Отдел": "Продажи",
        "Зарплата": 88000,
        "Стаж работы": 8,
    },
]

CLIENT_RECORDS = [
    [1, "Иван", 34, "Москва", 120000, "Хорошая"],
    [2, "Ольга", 27, "Санкт-Петербург", 80000, "Средняя"],
    [3, "Алексей", 45, "Казань", 150000, "Плохая"],
    [4, "Мария", 38, "Новосибирск", 200000, "Хорошая"],
    [5, "Сергей", 29, "Екатеринбург", 95000, "Средняя"],
    [6, "Анна", 50, "Воронеж", 300000, "Отличная"],
    [7, "Дмитрий", 31, "Челябинск", 140000, "Средняя"],
    [8, "Елена", 40, "Краснодар", 175000, "Хорошая"],
    [9, "Виктор", 28, "Ростов-на-Дону", 110000, "Плохая"],
    [10, "Алиса", 33, "Уфа", 98000, "Средняя"],
    [11, "Павел", 46, "Омск", 250000, "Хорошая"],
    [12, "Светлана", 37, "Пермь", 210000, "Отличная"],
    [13, "Роман", 41, "Тюмень", 135000, "Средняя"],
    [14, "Татьяна", 25, "Саратов", 155000, "Хорошая"],
    [15, "Николай", 39, "Самара", 125000, "Средняя"],
    [16, "Валерия", 42, "Волгоград", 180000, "Плохая"],
    [17, "Григорий", 49, "Барнаул", 275000, "Отличная"],
    [18, "Юлия", 50, "Иркутск", 320000, "Хорошая"],
    [19, "Степан", 30, "Хабаровск", 105000, "Средняя"],
    [20, "Василиса", 35, "Томск", 90000, "Плохая"],
]

CLIENT_COLUMNS = [
    "ID",
    "Имя",
    "Возраст",
    "Город",
    "Баланс на счете",
    "Кредитная история",
]

MISSING_CLIENT_RECORDS = [
    [1, "Иван", 34.0, "Москва", 120000.0, "Хорошая"],
    [2, "Ольга", 27.0, "Санкт-Петербург", np.nan, "Средняя"],
    [3, "Алексей", np.nan, "Казань", 150000.0, "Плохая"],
    [4, "Мария", 38.0, np.nan, 200000.0, "Хорошая"],
    [5, "Сергей", 29.0, "Екатеринбург", np.nan, np.nan],
    [6, np.nan, 50.0, "Воронеж", 300000.0, "Отличная"],
    [7, "Дмитрий", 31.0, np.nan, 140000.0, "Средняя"],
    [8, "Елена", 40.0, "Краснодар", 175000.0, "Хорошая"],
    [9, "Виктор", np.nan, "Ростов-на-Дону", 110000.0, np.nan],
    [10, "Алиса", 33.0, "Уфа", np.nan, "Средняя"],
    [11, "Павел", 46.0, "Омск", 250000.0, "Хорошая"],
    [12, np.nan, 37.0, "Пермь", 210000.0, "Отличная"],
    [13, "Роман", 41.0, np.nan, 135000.0, "Средняя"],
    [14, "Татьяна", 25.0, "Саратов", 155000.0, np.nan],
    [15, "Николай", np.nan, "Самара", 125000.0, "Средняя"],
    [16, "Валерия", 42.0, np.nan, np.nan, "Плохая"],
    [17, "Григорий", 49.0, "Барнаул", 275000.0, "Отличная"],
    [18, "Юлия", np.nan, "Иркутск", 320000.0, "Хорошая"],
    [19, "Степан", 30.0, "Хабаровск", 105000.0, "Средняя"],
    [20, "Василиса", 35.0, "Томск", 90000.0, "Плохая"],
]

employees_df = pd.DataFrame(EMPLOYEE_RECORDS)
clients_df = pd.DataFrame(CLIENT_RECORDS, columns=CLIENT_COLUMNS)
clients_missing_df = pd.DataFrame(
    MISSING_CLIENT_RECORDS,
    columns=CLIENT_COLUMNS,
)

display(employees_df.head())
display(clients_df.head())
display(clients_missing_df.head())

   ID      Имя  Возраст    Должность      Отдел  Зарплата  Стаж работы
0   1     Иван       25      Инженер         IT     60000            2
1   2    Ольга       30     Аналитик  Маркетинг     75000            5
2   3  Алексей       40     Менеджер    Продажи     90000           15
3   4    Мария       35  Программист         IT     80000            7
4   5   Сергей       28   Специалист         HR     50000            3

   ID      Имя  Возраст            Город  Баланс на счете Кредитная история
0   1     Иван       34           Москва           120000           Хорошая
1   2    Ольга       27  Санкт-Петербург            80000           Средняя
2   3  Алексей       45           Казань           150000            Плохая
3   4    Мария       38      Новосибирск           200000           Хорошая
4   5   Сергей       29     Екатеринбург            95000           Средняя

   ID      Имя  Возраст            Город  Баланс на счете Кредитная история
0   1     Иван     34.0           Москва         120000.0           Хорошая
1   2    Ольга     27.0  Санкт-Петербург              NaN           Средняя
2   3  Алексей      NaN           Казань         150000.0            Плохая
3   4    Мария     38.0              NaN         200000.0           Хорошая
4   5   Сергей     29.0     Екатеринбург              NaN               NaN

## Задание 1. Создание "DataFrame" разными способами

    **Условие.**

    1. Создайте "DataFrame" из словаря списков с данными о пяти
       сотрудниках, взяв данные из таблицы 1.
    2. Создайте "DataFrame" из списка словарей с теми же данными.
    3. Создайте "DataFrame" из массива "NumPy", заполненного случайными
       числами от 20 до 60 для возраста сотрудников.
    4. Проверьте типы данных в каждом столбце с помощью ".info()".

In [46]:
first_five_employees = EMPLOYEE_RECORDS[:5]

employee_dict = {
    column: [row[column] for row in first_five_employees]
    for column in employees_df.columns
}
df_from_dict = pd.DataFrame(employee_dict)

print("DataFrame из словаря списков:")
display(df_from_dict)

print("Информация о DataFrame из словаря списков:")
df_from_dict.info()

DataFrame из словаря списков:

   ID      Имя  Возраст    Должность      Отдел  Зарплата  Стаж работы
0   1     Иван       25      Инженер         IT     60000            2
1   2    Ольга       30     Аналитик  Маркетинг     75000            5
2   3  Алексей       40     Менеджер    Продажи     90000           15
3   4    Мария       35  Программист         IT     80000            7
4   5   Сергей       28   Специалист         HR     50000            3

Информация о DataFrame из словаря списков:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           5 non-null      int64
 1   Имя          5 non-null      object
 2   Возраст      5 non-null      int64
 3   Должность    5 non-null      object
 4   Отдел        5 non-null      object
 5   Зарплата     5 non-null      int64
 6   Стаж работы  5 non-null      int64
dtypes: int64(4), object(3)
memory usage: 412.0+ bytes

In [47]:
df_from_records = pd.DataFrame(first_five_employees)

print("DataFrame из списка словарей:")
display(df_from_records)

print("Информация о DataFrame из списка словарей:")
df_from_records.info()

DataFrame из списка словарей:

   ID      Имя  Возраст    Должность      Отдел  Зарплата  Стаж работы
0   1     Иван       25      Инженер         IT     60000            2
1   2    Ольга       30     Аналитик  Маркетинг     75000            5
2   3  Алексей       40     Менеджер    Продажи     90000           15
3   4    Мария       35  Программист         IT     80000            7
4   5   Сергей       28   Специалист         HR     50000            3

Информация о DataFrame из списка словарей:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           5 non-null      int64
 1   Имя          5 non-null      object
 2   Возраст      5 non-null      int64
 3   Должность    5 non-null      object
 4   Отдел        5 non-null      object
 5   Зарплата     5 non-null      int64
 6   Стаж работы  5 non-null      int64
dtypes: int64(4), object(3)
memory usage: 412.0+ bytes

In [48]:
rng = np.random.default_rng(seed=42)
random_ages = rng.integers(low=20, high=61, size=(5, 1))
df_from_numpy = pd.DataFrame(random_ages, columns=["Возраст"])

print("DataFrame из массива NumPy со случайными возрастами:")
display(df_from_numpy)

print("Информация о DataFrame из массива NumPy:")
df_from_numpy.info()

DataFrame из массива NumPy со случайными возрастами:

   Возраст
0       23
1       51
2       46
3       37
4       37

Информация о DataFrame из массива NumPy:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Возраст  5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

## Задание 2. Чтение данных из файлов ("CSV", "Excel", "JSON")

    **Условие.**

    Используйте предоставленные таблицы и сохраните их в файлы перед
    чтением.

    1. Сохраните таблицу 1 в "CSV" и затем загрузите ее обратно в
       "DataFrame".
    2. Запишите таблицу 2 в "Excel" ("data.xlsx", лист "Клиенты") и
       прочитайте ее в "DataFrame".
    3. Экспортируйте таблицу 1 в формат "JSON" и затем прочитайте ее
       обратно в "DataFrame".

    Выведите первые 5 строк загруженных "DataFrame".

In [49]:
csv_path = DATA_DIR / "employees.csv"
excel_path = DATA_DIR / "data.xlsx"
json_path = DATA_DIR / "employees.json"

employees_df.to_csv(csv_path, index=False, encoding="utf-8-sig")
clients_df.to_excel(excel_path, sheet_name="Клиенты", index=False)
employees_df.to_json(json_path, orient="records", force_ascii=False)

employees_from_csv = pd.read_csv(csv_path)
clients_from_excel = pd.read_excel(excel_path, sheet_name="Клиенты")
employees_from_json = pd.read_json(json_path, orient="records")

print("Первые 5 строк таблицы 1, загруженной из CSV:")
display(employees_from_csv.head())

print("Первые 5 строк таблицы 2, загруженной из Excel:")
display(clients_from_excel.head())

print("Первые 5 строк таблицы 1, загруженной из JSON:")
display(employees_from_json.head())

Первые 5 строк таблицы 1, загруженной из CSV:

   ID      Имя  Возраст    Должность      Отдел  Зарплата  Стаж работы
0   1     Иван       25      Инженер         IT     60000            2
1   2    Ольга       30     Аналитик  Маркетинг     75000            5
2   3  Алексей       40     Менеджер    Продажи     90000           15
3   4    Мария       35  Программист         IT     80000            7
4   5   Сергей       28   Специалист         HR     50000            3

Первые 5 строк таблицы 2, загруженной из Excel:

   ID      Имя  Возраст            Город  Баланс на счете Кредитная история
0   1     Иван       34           Москва           120000           Хорошая
1   2    Ольга       27  Санкт-Петербург            80000           Средняя
2   3  Алексей       45           Казань           150000            Плохая
3   4    Мария       38      Новосибирск           200000           Хорошая
4   5   Сергей       29     Екатеринбург            95000           Средняя

Первые 5 строк таблицы 1, загруженной из JSON:

   ID      Имя  Возраст    Должность      Отдел  Зарплата  Стаж работы
0   1     Иван       25      Инженер         IT     60000            2
1   2    Ольга       30     Аналитик  Маркетинг     75000            5
2   3  Алексей       40     Менеджер    Продажи     90000           15
3   4    Мария       35  Программист         IT     80000            7
4   5   Сергей       28   Специалист         HR     50000            3

## Задание 3. Доступ к данным (".loc", ".iloc", ".at", ".iat")

    **Условие.**

    Используя таблицу 1:

    1. Получите информацию о сотруднике с "ID = 5" с помощью ".loc[]".
    2. Выведите возраст третьего сотрудника в таблице с ".iloc[]".
    3. Выведите название отдела для сотрудника "Мария" с ".at[]".
    4. Выведите зарплату сотрудника, находящегося в четвертой строке и
       пятом столбце, используя ".iat[]".

    Объясните разницу между ".loc[]", ".iloc[]", ".at[]", ".iat[]".

In [50]:
employees_by_id = employees_df.set_index("ID")

employee_id_5 = employees_by_id.loc[5]
third_employee_age = employees_by_id.iloc[2]["Возраст"]
maria_id = employees_by_id.index[employees_by_id["Имя"] == "Мария"][0]
maria_department = employees_by_id.at[maria_id, "Отдел"]
fourth_row_fifth_column_salary = employees_by_id.iat[3, 4]

print("Сотрудник с ID = 5:")
display(employee_id_5.to_frame().T)

print(f"Возраст третьего сотрудника: {third_employee_age}")
print(f"Отдел сотрудника Мария: {maria_department}")
print(
    "Зарплата в четвертой строке и пятом столбце: "
    f"{fourth_row_fifth_column_salary}"
)

Сотрудник с ID = 5:

      Имя Возраст   Должность Отдел Зарплата Стаж работы
5  Сергей      28  Специалист    HR    50000           3

Возраст третьего сотрудника: 40
Отдел сотрудника Мария: IT
Зарплата в четвертой строке и пятом столбце: 80000

**Пояснение.**

    ".loc[]" используется для доступа к данным по меткам индекса и
    названиям столбцов. ".iloc[]" используется для доступа по числовым
    позициям строк и столбцов. ".at[]" предназначен для быстрого доступа
    к одному значению по метке строки и названию столбца. ".iat[]"
    предназначен для быстрого доступа к одному значению по числовым
    позициям строки и столбца.

## Задание 4. Добавление новых столбцов и строк

    **Условие.**

    Используя таблицу 1:

    1. Добавьте новый столбец "Категория зарплаты": "Низкая", если
       зарплата меньше 60000; "Средняя", если зарплата от 60000 до
       100000; "Высокая", если зарплата не меньше 100000.
    2. Добавьте нового сотрудника с данными: "Антон", 32,
       "Разработчик", "IT", 85000, 6.
    3. Добавьте двух новых сотрудников одновременно, используя
       "pd.concat()".

    Выведите обновленный "DataFrame".

In [51]:
def get_salary_category(salary):
    """Return a text category for an employee salary."""
    if salary < 60000:
        return "Низкая"
    if salary < 100000:
        return "Средняя"
    return "Высокая"


updated_employees = employees_by_id.copy()
updated_employees["Категория зарплаты"] = updated_employees[
    "Зарплата"
].apply(get_salary_category)

print("После добавления столбца 'Категория зарплаты':")
display(updated_employees)

После добавления столбца 'Категория зарплаты':

         Имя  Возраст        Должность          Отдел  Зарплата  Стаж работы Категория зарплаты
ID
1       Иван       25          Инженер             IT     60000            2            Средняя
2      Ольга       30         Аналитик      Маркетинг     75000            5            Средняя
3    Алексей       40         Менеджер        Продажи     90000           15            Средняя
4      Мария       35      Программист             IT     80000            7            Средняя
5     Сергей       28       Специалист             HR     50000            3             Низкая
6       Анна       32      Разработчик             IT     85000            6            Средняя
7    Дмитрий       45               HR             HR     48000           12             Низкая
8      Елена       29       Маркетолог      Маркетинг     70000            4            Средняя
9     Виктор       31            Юрист    Юридический     95000           10            Средняя
10     Алиса       27         Дизайнер         Дизайн     62000            5            Средняя
11     Павел       33    Администратор  Администрация     55000            7             Низкая
12  Светлана       26      Тестировщик   Тестирование     67000            2            Средняя
13     Роман       42        Финансист        Финансы    105000           20            Высокая
14   Татьяна       37         Редактор       Редакция     72000            9            Средняя
15   Николай       39           Логист      Логистика     75000           11            Средняя
16   Валерия       24   SEO-специалист            SEO     64000            3            Средняя
17  Григорий       50        Бухгалтер    Бухгалтерия    110000           25            Высокая
18      Юлия       45         Директор        Финансы    150000           20            Высокая
19    Степан       41        Экономист      Экономика     98000           14            Средняя
20  Василиса       38  Проект-менеджер        Продажи     88000            8            Средняя

In [52]:
anton_salary = 85000
updated_employees.loc[21] = {
    "Имя": "Антон",
    "Возраст": 32,
    "Должность": "Разработчик",
    "Отдел": "IT",
    "Зарплата": anton_salary,
    "Стаж работы": 6,
    "Категория зарплаты": get_salary_category(anton_salary),
}

print("После добавления сотрудника Антон:")
display(updated_employees.tail())

После добавления сотрудника Антон:

         Имя  Возраст        Должность        Отдел  Зарплата  Стаж работы Категория зарплаты
ID
17  Григорий       50        Бухгалтер  Бухгалтерия    110000           25            Высокая
18      Юлия       45         Директор      Финансы    150000           20            Высокая
19    Степан       41        Экономист    Экономика     98000           14            Средняя
20  Василиса       38  Проект-менеджер      Продажи     88000            8            Средняя
21     Антон       32      Разработчик           IT     85000            6            Средняя

In [53]:
new_employee_records = [
    {
        "Имя": "Кирилл",
        "Возраст": 29,
        "Должность": "Аналитик данных",
        "Отдел": "IT",
        "Зарплата": 92000,
        "Стаж работы": 4,
    },
    {
        "Имя": "Евгения",
        "Возраст": 36,
        "Должность": "Руководитель проекта",
        "Отдел": "Продажи",
        "Зарплата": 115000,
        "Стаж работы": 9,
    },
]

new_employees = pd.DataFrame(new_employee_records, index=[22, 23])
new_employees["Категория зарплаты"] = new_employees["Зарплата"].apply(
    get_salary_category
)
new_employees.index.name = "ID"
updated_employees = pd.concat([updated_employees, new_employees])

print("После добавления двух новых сотрудников через pd.concat():")
display(updated_employees)

После добавления двух новых сотрудников через pd.concat():

         Имя  Возраст             Должность          Отдел  Зарплата  Стаж работы Категория зарплаты
ID
1       Иван       25               Инженер             IT     60000            2            Средняя
2      Ольга       30              Аналитик      Маркетинг     75000            5            Средняя
3    Алексей       40              Менеджер        Продажи     90000           15            Средняя
4      Мария       35           Программист             IT     80000            7            Средняя
5     Сергей       28            Специалист             HR     50000            3             Низкая
6       Анна       32           Разработчик             IT     85000            6            Средняя
7    Дмитрий       45                    HR             HR     48000           12             Низкая
8      Елена       29            Маркетолог      Маркетинг     70000            4            Средняя
9     Виктор       31                 Юрист    Юридический     95000           10            Средняя
10     Алиса       27              Дизайнер         Дизайн     62000            5            Средняя
11     Павел       33         Администратор  Администрация     55000            7             Низкая
12  Светлана       26           Тестировщик   Тестирование     67000            2            Средняя
13     Роман       42             Финансист        Финансы    105000           20            Высокая
14   Татьяна       37              Редактор       Редакция     72000            9            Средняя
15   Николай       39                Логист      Логистика     75000           11            Средняя
16   Валерия       24        SEO-специалист            SEO     64000            3            Средняя
17  Григорий       50             Бухгалтер    Бухгалтерия    110000           25            Высокая
18      Юлия       45              Директор        Финансы    150000           20            Высокая
19    Степан       41             Экономист      Экономика     98000           14            Средняя
20  Василиса       38       Проект-менеджер        Продажи     88000            8            Средняя
21     Антон       32           Разработчик             IT     85000            6            Средняя
22    Кирилл       29       Аналитик данных             IT     92000            4            Средняя
23   Евгения       36  Руководитель проекта        Продажи    115000            9            Высокая

## Задание 5. Удаление строк и столбцов

    **Условие.**

    Используя таблицу 1:

    1. Удалите столбец "Категория зарплаты" с ".drop()".
    2. Удалите строку с "ID = 10".
    3. Удалите все строки, где "Стаж работы < 3".
    4. Удалите все столбцы, кроме "Имя", "Должность", "Зарплата".

    Выведите "DataFrame" после каждого шага.

In [54]:
deleted_data = updated_employees.copy()

deleted_data = deleted_data.drop(columns=["Категория зарплаты"])
print("Шаг 1. После удаления столбца 'Категория зарплаты':")
display(deleted_data)

deleted_data = deleted_data.drop(index=10)
print("Шаг 2. После удаления строки с ID = 10:")
display(deleted_data)

deleted_data = deleted_data[deleted_data["Стаж работы"] >= 3]
print("Шаг 3. После удаления строк, где стаж работы меньше 3 лет:")
display(deleted_data)

deleted_data = deleted_data[["Имя", "Должность", "Зарплата"]]
print("Шаг 4. После удаления всех столбцов, кроме нужных:")
display(deleted_data)

Шаг 1. После удаления столбца 'Категория зарплаты':

         Имя  Возраст             Должность          Отдел  Зарплата  Стаж работы
ID
1       Иван       25               Инженер             IT     60000            2
2      Ольга       30              Аналитик      Маркетинг     75000            5
3    Алексей       40              Менеджер        Продажи     90000           15
4      Мария       35           Программист             IT     80000            7
5     Сергей       28            Специалист             HR     50000            3
6       Анна       32           Разработчик             IT     85000            6
7    Дмитрий       45                    HR             HR     48000           12
8      Елена       29            Маркетолог      Маркетинг     70000            4
9     Виктор       31                 Юрист    Юридический     95000           10
10     Алиса       27              Дизайнер         Дизайн     62000            5
11     Павел       33         Администратор  Администрация     55000            7
12  Светлана       26           Тестировщик   Тестирование     67000            2
13     Роман       42             Финансист        Финансы    105000           20
14   Татьяна       37              Редактор       Редакция     72000            9
15   Николай       39                Логист      Логистика     75000           11
16   Валерия       24        SEO-специалист            SEO     64000            3
17  Григорий       50             Бухгалтер    Бухгалтерия    110000           25
18      Юлия       45              Директор        Финансы    150000           20
19    Степан       41             Экономист      Экономика     98000           14
20  Василиса       38       Проект-менеджер        Продажи     88000            8
21     Антон       32           Разработчик             IT     85000            6
22    Кирилл       29       Аналитик данных             IT     92000            4
23   Евгения       36  Руководитель проекта        Продажи    115000            9

Шаг 2. После удаления строки с ID = 10:

         Имя  Возраст             Должность          Отдел  Зарплата  Стаж работы
ID
1       Иван       25               Инженер             IT     60000            2
2      Ольга       30              Аналитик      Маркетинг     75000            5
3    Алексей       40              Менеджер        Продажи     90000           15
4      Мария       35           Программист             IT     80000            7
5     Сергей       28            Специалист             HR     50000            3
6       Анна       32           Разработчик             IT     85000            6
7    Дмитрий       45                    HR             HR     48000           12
8      Елена       29            Маркетолог      Маркетинг     70000            4
9     Виктор       31                 Юрист    Юридический     95000           10
11     Павел       33         Администратор  Администрация     55000            7
12  Светлана       26           Тестировщик   Тестирование     67000            2
13     Роман       42             Финансист        Финансы    105000           20
14   Татьяна       37              Редактор       Редакция     72000            9
15   Николай       39                Логист      Логистика     75000           11
16   Валерия       24        SEO-специалист            SEO     64000            3
17  Григорий       50             Бухгалтер    Бухгалтерия    110000           25
18      Юлия       45              Директор        Финансы    150000           20
19    Степан       41             Экономист      Экономика     98000           14
20  Василиса       38       Проект-менеджер        Продажи     88000            8
21     Антон       32           Разработчик             IT     85000            6
22    Кирилл       29       Аналитик данных             IT     92000            4
23   Евгения       36  Руководитель проекта        Продажи    115000            9

Шаг 3. После удаления строк, где стаж работы меньше 3 лет:

         Имя  Возраст             Должность          Отдел  Зарплата  Стаж работы
ID
2      Ольга       30              Аналитик      Маркетинг     75000            5
3    Алексей       40              Менеджер        Продажи     90000           15
4      Мария       35           Программист             IT     80000            7
5     Сергей       28            Специалист             HR     50000            3
6       Анна       32           Разработчик             IT     85000            6
7    Дмитрий       45                    HR             HR     48000           12
8      Елена       29            Маркетолог      Маркетинг     70000            4
9     Виктор       31                 Юрист    Юридический     95000           10
11     Павел       33         Администратор  Администрация     55000            7
13     Роман       42             Финансист        Финансы    105000           20
14   Татьяна       37              Редактор       Редакция     72000            9
15   Николай       39                Логист      Логистика     75000           11
16   Валерия       24        SEO-специалист            SEO     64000            3
17  Григорий       50             Бухгалтер    Бухгалтерия    110000           25
18      Юлия       45              Директор        Финансы    150000           20
19    Степан       41             Экономист      Экономика     98000           14
20  Василиса       38       Проект-менеджер        Продажи     88000            8
21     Антон       32           Разработчик             IT     85000            6
22    Кирилл       29       Аналитик данных             IT     92000            4
23   Евгения       36  Руководитель проекта        Продажи    115000            9

Шаг 4. После удаления всех столбцов, кроме нужных:

         Имя             Должность  Зарплата
ID
2      Ольга              Аналитик     75000
3    Алексей              Менеджер     90000
4      Мария           Программист     80000
5     Сергей            Специалист     50000
6       Анна           Разработчик     85000
7    Дмитрий                    HR     48000
8      Елена            Маркетолог     70000
9     Виктор                 Юрист     95000
11     Павел         Администратор     55000
13     Роман             Финансист    105000
14   Татьяна              Редактор     72000
15   Николай                Логист     75000
16   Валерия        SEO-специалист     64000
17  Григорий             Бухгалтер    110000
18      Юлия              Директор    150000
19    Степан             Экономист     98000
20  Василиса       Проект-менеджер     88000
21     Антон           Разработчик     85000
22    Кирилл       Аналитик данных     92000
23   Евгения  Руководитель проекта    115000

## Задание 6. Фильтрация данных ("query", "isin", "between")

    **Условие.**

    Используя таблицу 2:

    1. Выберите всех клиентов из "Москва" или "Санкт-Петербург",
       используя ".isin()".
    2. Выберите клиентов, у которых "Баланс на счете" от 100000 до
       250000, используя ".between()".
    3. Отфильтруйте клиентов, у которых "Кредитная история" —
       "Хорошая" и "Баланс на счете > 150000", используя ".query()".

    Выведите результаты каждого фильтра.

In [55]:
selected_cities = ["Москва", "Санкт-Петербург"]
clients_from_selected_cities = clients_df[
    clients_df["Город"].isin(selected_cities)
]

clients_with_balance_range = clients_df[
    clients_df["Баланс на счете"].between(100000, 250000)
]

clients_good_credit = clients_df.query(
    "`Кредитная история` == 'Хорошая' and `Баланс на счете` > 150000"
    )

print("Клиенты из Москвы или Санкт-Петербурга:")
display(clients_from_selected_cities)

print("Клиенты с балансом от 100000 до 250000:")
display(clients_with_balance_range)

print("Клиенты с хорошей кредитной историей и балансом больше 150000:")
display(clients_good_credit)

Клиенты из Москвы или Санкт-Петербурга:

   ID    Имя  Возраст            Город  Баланс на счете Кредитная история
0   1   Иван       34           Москва           120000           Хорошая
1   2  Ольга       27  Санкт-Петербург            80000           Средняя

Клиенты с балансом от 100000 до 250000:

    ID       Имя  Возраст           Город  Баланс на счете Кредитная история
0    1      Иван       34          Москва           120000           Хорошая
2    3   Алексей       45          Казань           150000            Плохая
3    4     Мария       38     Новосибирск           200000           Хорошая
6    7   Дмитрий       31       Челябинск           140000           Средняя
7    8     Елена       40       Краснодар           175000           Хорошая
8    9    Виктор       28  Ростов-на-Дону           110000            Плохая
10  11     Павел       46            Омск           250000           Хорошая
11  12  Светлана       37           Пермь           210000          Отличная
12  13     Роман       41          Тюмень           135000           Средняя
13  14   Татьяна       25         Саратов           155000           Хорошая
14  15   Николай       39          Самара           125000           Средняя
15  16   Валерия       42       Волгоград           180000            Плохая
18  19    Степан       30       Хабаровск           105000           Средняя

Клиенты с хорошей кредитной историей и балансом больше 150000:

    ID      Имя  Возраст        Город  Баланс на счете Кредитная история
3    4    Мария       38  Новосибирск           200000           Хорошая
7    8    Елена       40    Краснодар           175000           Хорошая
10  11    Павел       46         Омск           250000           Хорошая
13  14  Татьяна       25      Саратов           155000           Хорошая
17  18     Юлия       50      Иркутск           320000           Хорошая

## Задание 7. Подсчет значений ("count", "value_counts", "nunique")

    **Условие.**

    Используя таблицу 2:

    1. Подсчитайте количество непустых значений в каждом столбце
       (".count()").
    2. Определите частоту встречаемости значений в "Город"
       (".value_counts()").
    3. Найдите количество уникальных значений в "Город", "Возраст",
       "Баланс на счете" (".nunique()").

    Выведите результаты.

In [56]:
non_empty_counts = clients_df.count()
city_value_counts = clients_df["Город"].value_counts()
unique_counts = clients_df[[
    "Город",
    "Возраст",
    "Баланс на счете",
]].nunique()

print("Количество непустых значений в каждом столбце:")
display(non_empty_counts.to_frame(name="Количество"))

print("Частота встречаемости значений в столбце 'Город':")
display(city_value_counts.to_frame(name="Частота"))

print("Количество уникальных значений:")
display(unique_counts.to_frame(name="Уникальных значений"))

Количество непустых значений в каждом столбце:

                   Количество
ID                         20
Имя                        20
Возраст                    20
Город                      20
Баланс на счете            20
Кредитная история          20

Частота встречаемости значений в столбце 'Город':

                 Частота
Город
Москва                 1
Санкт-Петербург        1
Хабаровск              1
Иркутск                1
Барнаул                1
Волгоград              1
Самара                 1
Саратов                1
Тюмень                 1
Пермь                  1
Омск                   1
Уфа                    1
Ростов-на-Дону         1
Краснодар              1
Челябинск              1
Воронеж                1
Екатеринбург           1
Новосибирск            1
Казань                 1
Томск                  1

Количество уникальных значений:

                 Уникальных значений
Город                             20
Возраст                           19
Баланс на счете                   20

## Задание 8. Обнаружение пропусков ("isna", "notna")

    **Условие.**

    Используя таблицу 3:

    1. Подсчитайте количество "NaN" в каждом столбце (".isna().sum()").
    2. Подсчитайте количество заполненных значений в каждом столбце
       (".notna().sum()").
    3. Выведите "DataFrame", оставив только строки, где нет пропущенных
       значений.

    Объясните разницу между ".isna()" и ".notna()".

In [57]:
missing_counts = clients_missing_df.isna().sum()
filled_counts = clients_missing_df.notna().sum()
rows_without_missing = clients_missing_df.dropna()

print("Количество NaN в каждом столбце:")
display(missing_counts.to_frame(name="NaN"))

print("Количество заполненных значений в каждом столбце:")
display(filled_counts.to_frame(name="Заполнено"))

print("Строки без пропущенных значений:")
display(rows_without_missing)

Количество NaN в каждом столбце:

                   NaN
ID                   0
Имя                  2
Возраст              4
Город                4
Баланс на счете      4
Кредитная история    3

Количество заполненных значений в каждом столбце:

                   Заполнено
ID                        20
Имя                       18
Возраст                   16
Город                     16
Баланс на счете           16
Кредитная история         17

Строки без пропущенных значений:

    ID       Имя  Возраст      Город  Баланс на счете Кредитная история
0    1      Иван     34.0     Москва         120000.0           Хорошая
7    8     Елена     40.0  Краснодар         175000.0           Хорошая
10  11     Павел     46.0       Омск         250000.0           Хорошая
16  17  Григорий     49.0    Барнаул         275000.0          Отличная
18  19    Степан     30.0  Хабаровск         105000.0           Средняя
19  20  Василиса     35.0      Томск          90000.0            Плохая

**Пояснение.**

    Метод ".isna()" возвращает логическую таблицу, где "True" означает,
    что значение является пропущенным ("NaN", "None", "NaT"). Метод
    ".notna()" возвращает обратный результат: "True" означает, что
    значение заполнено и не является пропуском.

## Индивидуальное практическое задание. Вариант 1

**Условие.**

Написать программу на языке Python. Приложение должно использовать
графический интерфейс пользователя на "tkinter", работать с датой и
временем через "datetime", читать и сохранять данные в формат "Parquet",
выполнять валидацию сохраненных данных и поддерживать удаление данных
по одной из колонок "DataFrame".

Вариант 1: использовать "DataFrame", содержащий колонки "Фамилия и
инициалы", "Номер группы", "Успеваемость" по предметам. Программа должна
позволять вводить данные с клавиатуры и добавлять новые строки в
"DataFrame"; записи должны быть упорядочены по возрастанию номера
группы; нужно выводить фамилии и номера групп всех студентов, если
средний балл студента больше 4.0. Если таких студентов нет, необходимо
выводить соответствующее сообщение.

In [58]:
student_gui_code = r'''
from __future__ import annotations

from datetime import datetime
from pathlib import Path
import tkinter as tk
from tkinter import filedialog, messagebox, ttk

import pandas as pd

APP_DIR = Path(__file__).resolve().parent
DEFAULT_FILE = APP_DIR / "students.parquet"

DATA_COLUMNS = [
    "Фамилия и инициалы",
    "Номер группы",
    "Математика",
    "Программирование",
    "Базы данных",
    "Дата добавления",
]
SUBJECT_COLUMNS = ["Математика", "Программирование", "Базы данных"]
GRADE_MIN = 2
GRADE_MAX = 5


class StudentApp:
    """Tkinter application for managing student performance data."""

    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        self.root.title("Успеваемость студентов")
        self.root.geometry("1100x650")

        self.file_path_var = tk.StringVar(value=str(DEFAULT_FILE))
        self.fio_var = tk.StringVar()
        self.group_var = tk.StringVar()
        self.math_var = tk.StringVar()
        self.programming_var = tk.StringVar()
        self.databases_var = tk.StringVar()
        self.delete_column_var = tk.StringVar(value=DATA_COLUMNS[0])
        self.delete_value_var = tk.StringVar()
        self.status_var = tk.StringVar(value="Готово")

        self.students = self.load_students(DEFAULT_FILE)

        self.create_widgets()
        self.refresh_table(self.students)

    def create_widgets(self) -> None:
        """Create all graphical interface widgets."""
        file_frame = ttk.LabelFrame(self.root, text="Файл Parquet")
        file_frame.pack(fill="x", padx=10, pady=6)

        file_entry = ttk.Entry(
            file_frame,
            textvariable=self.file_path_var,
        )
        file_entry.pack(side="left", fill="x", expand=True, padx=6, pady=6)

        ttk.Button(
            file_frame,
            text="Выбрать",
            command=self.choose_file,
        ).pack(side="left", padx=4)
        ttk.Button(
            file_frame,
            text="Загрузить",
            command=self.load_from_selected_file,
        ).pack(side="left", padx=4)
        ttk.Button(
            file_frame,
            text="Сохранить",
            command=self.save_to_selected_file,
        ).pack(side="left", padx=4)
        ttk.Button(
            file_frame,
            text="Проверить Parquet",
            command=self.validate_selected_file,
        ).pack(side="left", padx=4)

        input_frame = ttk.LabelFrame(self.root, text="Добавление студента")
        input_frame.pack(fill="x", padx=10, pady=6)

        fields = [
            ("Фамилия и инициалы", self.fio_var),
            ("Номер группы", self.group_var),
            ("Математика", self.math_var),
            ("Программирование", self.programming_var),
            ("Базы данных", self.databases_var),
        ]

        for index, (label, variable) in enumerate(fields):
            ttk.Label(input_frame, text=label).grid(
                row=0,
                column=index,
                padx=4,
                pady=2,
                sticky="w",
            )
            ttk.Entry(input_frame, textvariable=variable, width=22).grid(
                row=1,
                column=index,
                padx=4,
                pady=2,
                sticky="ew",
            )
            input_frame.columnconfigure(index, weight=1)

        ttk.Button(
            input_frame,
            text="Добавить",
            command=self.add_student,
        ).grid(row=1, column=len(fields), padx=4, pady=2)
        ttk.Button(
            input_frame,
            text="Очистить поля",
            command=self.clear_input_fields,
        ).grid(row=1, column=len(fields) + 1, padx=4, pady=2)

        action_frame = ttk.LabelFrame(self.root, text="Действия")
        action_frame.pack(fill="x", padx=10, pady=6)

        ttk.Button(
            action_frame,
            text="Показать всех",
            command=self.show_all_students,
        ).pack(side="left", padx=5, pady=6)
        ttk.Button(
            action_frame,
            text="Средний балл > 4.0",
            command=self.show_successful_students,
        ).pack(side="left", padx=5, pady=6)

        ttk.Label(action_frame, text="Удалить по колонке:").pack(
            side="left",
            padx=(20, 5),
        )
        ttk.Combobox(
            action_frame,
            values=DATA_COLUMNS,
            textvariable=self.delete_column_var,
            width=22,
            state="readonly",
        ).pack(side="left", padx=5)
        ttk.Entry(
            action_frame,
            textvariable=self.delete_value_var,
            width=24,
        ).pack(side="left", padx=5)
        ttk.Button(
            action_frame,
            text="Удалить",
            command=self.delete_rows_by_column,
        ).pack(side="left", padx=5)

        table_frame = ttk.Frame(self.root)
        table_frame.pack(fill="both", expand=True, padx=10, pady=6)

        self.tree = ttk.Treeview(table_frame, show="headings")
        vertical_scroll = ttk.Scrollbar(
            table_frame,
            orient="vertical",
            command=self.tree.yview,
        )
        horizontal_scroll = ttk.Scrollbar(
            table_frame,
            orient="horizontal",
            command=self.tree.xview,
        )
        self.tree.configure(
            yscrollcommand=vertical_scroll.set,
            xscrollcommand=horizontal_scroll.set,
        )

        self.tree.grid(row=0, column=0, sticky="nsew")
        vertical_scroll.grid(row=0, column=1, sticky="ns")
        horizontal_scroll.grid(row=1, column=0, sticky="ew")
        table_frame.rowconfigure(0, weight=1)
        table_frame.columnconfigure(0, weight=1)

        ttk.Label(
            self.root,
            textvariable=self.status_var,
            anchor="w",
        ).pack(fill="x", padx=10, pady=(0, 8))

    def choose_file(self) -> None:
        """Open a file dialog and select a Parquet file."""
        selected_path = filedialog.asksaveasfilename(
            defaultextension=".parquet",
            filetypes=[("Parquet files", "*.parquet"), ("All files", "*.*")],
            initialdir=str(APP_DIR),
            title="Выберите или создайте Parquet-файл",
        )
        if selected_path:
            self.file_path_var.set(selected_path)

    def load_students(self, path: Path) -> pd.DataFrame:
        """Load students from Parquet or return an empty DataFrame."""
        if not path.exists():
            return pd.DataFrame(columns=DATA_COLUMNS)

        try:
            students = pd.read_parquet(path, engine="pyarrow")
        except ImportError as error:
            self.show_pyarrow_error(error)
            return pd.DataFrame(columns=DATA_COLUMNS)
        except Exception as error:
            messagebox.showerror("Ошибка чтения", str(error))
            return pd.DataFrame(columns=DATA_COLUMNS)

        return self.prepare_students(students)

    @staticmethod
    def prepare_students(students: pd.DataFrame) -> pd.DataFrame:
        """Normalize columns, numeric values and sort by group number."""
        result = students.reindex(columns=DATA_COLUMNS).copy()

        if result.empty:
            return result

        numeric_columns = ["Номер группы", *SUBJECT_COLUMNS]
        for column in numeric_columns:
            result[column] = pd.to_numeric(result[column], errors="raise")

        return result.sort_values(
            by=["Номер группы", "Фамилия и инициалы"],
            ascending=[True, True],
        ).reset_index(drop=True)

    def save_students(self) -> bool:
        """Save current DataFrame to the selected Parquet file."""
        path = Path(self.file_path_var.get())
        path.parent.mkdir(parents=True, exist_ok=True)

        try:
            prepared_students = self.prepare_students(self.students)
            prepared_students.to_parquet(path, engine="pyarrow", index=False)
        except ImportError as error:
            self.show_pyarrow_error(error)
            return False
        except Exception as error:
            messagebox.showerror("Ошибка сохранения", str(error))
            return False

        self.students = prepared_students
        self.status_var.set(f"Данные сохранены: {path}")
        return True

    def load_from_selected_file(self) -> None:
        """Load data from the selected file and show it in the table."""
        path = Path(self.file_path_var.get())
        self.students = self.load_students(path)
        self.refresh_table(self.students)
        self.status_var.set(f"Загружено строк: {len(self.students)}")

    def save_to_selected_file(self) -> None:
        """Save data using the selected path."""
        if self.save_students():
            self.refresh_table(self.students)
            messagebox.showinfo("Сохранение", "Данные успешно сохранены.")

    def validate_selected_file(self) -> None:
        """Validate that the selected Parquet file is readable."""
        path = Path(self.file_path_var.get())

        if not path.exists():
            messagebox.showwarning("Проверка", "Файл еще не создан.")
            return

        try:
            students = pd.read_parquet(path, engine="pyarrow")
        except ImportError as error:
            self.show_pyarrow_error(error)
            return
        except Exception as error:
            messagebox.showerror("Проверка", f"Ошибка чтения: {error}")
            return

        missing_columns = [
            column for column in DATA_COLUMNS if column not in students.columns
        ]
        if missing_columns:
            messagebox.showerror(
                "Проверка",
                "Отсутствуют столбцы: " + ", ".join(missing_columns),
            )
            return

        messagebox.showinfo(
            "Проверка",
            "Файл Parquet корректен. "
            f"Строк: {len(students)}, столбцов: {len(students.columns)}.",
        )

    def add_student(self) -> None:
        """Validate input values and add a new student row."""
        try:
            student = self.get_student_from_form()
        except ValueError as error:
            messagebox.showwarning("Проверка данных", str(error))
            return

        self.students = pd.concat(
            [self.students, pd.DataFrame([student])],
            ignore_index=True,
        )
        self.students = self.prepare_students(self.students)

        if self.save_students():
            self.refresh_table(self.students)
            self.clear_input_fields()
            messagebox.showinfo("Добавление", "Студент добавлен.")

    def get_student_from_form(self) -> dict[str, object]:
        """Read and validate one student record from input fields."""
        fio = self.fio_var.get().strip()
        if not fio:
            raise ValueError("Введите фамилию и инициалы студента.")

        group_number = self.parse_positive_int(
            self.group_var.get(),
            "Номер группы",
        )
        math_grade = self.parse_grade(self.math_var.get(), "Математика")
        programming_grade = self.parse_grade(
            self.programming_var.get(),
            "Программирование",
        )
        databases_grade = self.parse_grade(
            self.databases_var.get(),
            "Базы данных",
        )

        return {
            "Фамилия и инициалы": fio,
            "Номер группы": group_number,
            "Математика": math_grade,
            "Программирование": programming_grade,
            "Базы данных": databases_grade,
            "Дата добавления": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        }

    @staticmethod
    def parse_positive_int(value: str, field_name: str) -> int:
        """Convert a string to a positive integer."""
        try:
            number = int(value)
        except ValueError as error:
            message = f"Поле '{field_name}' должно быть целым числом."
            raise ValueError(message) from error

        if number <= 0:
            raise ValueError(f"Поле '{field_name}' должно быть больше нуля.")
        return number

    @staticmethod
    def parse_grade(value: str, field_name: str) -> int:
        """Convert a string to a grade and validate its range."""
        try:
            grade = int(value)
        except ValueError as error:
            message = f"Оценка '{field_name}' должна быть целым числом."
            raise ValueError(message) from error

        if not GRADE_MIN <= grade <= GRADE_MAX:
            raise ValueError(
                f"Оценка '{field_name}' должна быть от {GRADE_MIN} до {GRADE_MAX}."
            )
        return grade

    def show_all_students(self) -> None:
        """Display all student records."""
        self.refresh_table(self.students)
        self.status_var.set(f"Показаны все записи: {len(self.students)}")

    def show_successful_students(self) -> None:
        """Show students whose average grade is greater than 4.0."""
        if self.students.empty:
            messagebox.showinfo("Результат", "Данные отсутствуют.")
            return

        students = self.prepare_students(self.students).copy()
        students["Средний балл"] = students[SUBJECT_COLUMNS].mean(axis=1)
        selected_students = students.loc[
            students["Средний балл"] > 4.0,
            ["Фамилия и инициалы", "Номер группы", "Средний балл"],
        ]

        if selected_students.empty:
            self.refresh_table(selected_students)
            messagebox.showinfo(
                "Результат",
                "Нет студентов со средним баллом выше 4.0.",
            )
            return

        self.refresh_table(selected_students)
        self.status_var.set(
            "Показаны студенты со средним баллом выше 4.0: "
            f"{len(selected_students)}"
        )

    def delete_rows_by_column(self) -> None:
        """Delete all rows where the chosen column equals the given value."""
        column = self.delete_column_var.get()
        value = self.delete_value_var.get().strip()

        if not value:
            messagebox.showwarning("Удаление", "Введите значение для удаления.")
            return

        if column not in self.students.columns:
            messagebox.showerror("Удаление", f"Столбец '{column}' не найден.")
            return

        old_length = len(self.students)
        mask = self.students[column].astype(str) != value
        self.students = self.students.loc[mask].reset_index(drop=True)
        deleted_count = old_length - len(self.students)

        if self.save_students():
            self.refresh_table(self.students)
            self.status_var.set(f"Удалено строк: {deleted_count}")
            messagebox.showinfo("Удаление", f"Удалено строк: {deleted_count}")

    def refresh_table(self, data: pd.DataFrame) -> None:
        """Refresh the Treeview widget with DataFrame content."""
        for item in self.tree.get_children():
            self.tree.delete(item)

        columns = list(data.columns)
        self.tree["columns"] = columns

        for column in columns:
            self.tree.heading(column, text=column)
            self.tree.column(column, width=160, minwidth=80, stretch=True)

        for _, row in data.iterrows():
            values = ["" if pd.isna(value) else value for value in row]
            self.tree.insert("", "end", values=values)

    def clear_input_fields(self) -> None:
        """Clear all input fields for adding a student."""
        self.fio_var.set("")
        self.group_var.set("")
        self.math_var.set("")
        self.programming_var.set("")
        self.databases_var.set("")

    @staticmethod
    def show_pyarrow_error(error: ImportError) -> None:
        """Show an explanation when Parquet dependencies are missing."""
        messagebox.showerror(
            "Не установлен pyarrow",
            "Для работы с Parquet установите пакет pyarrow:\n"
            "python -m pip install pyarrow\n\n"
            f"Подробности: {error}",
        )


def main() -> None:
    """Run the Tkinter application."""
    root = tk.Tk()
    app = StudentApp(root)
    root.mainloop()


if __name__ == "__main__":
    main()

'''

requirements_text = (
    "pandas>=2.0\n"
    "numpy>=1.24\n"
    "openpyxl>=3.1\n"
    "pyarrow>=15.0\n"
    "jupyter>=1.0\n"
)

app_path = DATA_DIR / "student_gui.py"
requirements_path = DATA_DIR / "requirements.txt"

app_path.write_text(student_gui_code, encoding="utf-8")
requirements_path.write_text(requirements_text, encoding="utf-8")
compile(student_gui_code, str(app_path), "exec")

print(f"Tkinter-приложение сохранено: {app_path}")
print(f"Файл зависимостей сохранен: {requirements_path}")

Tkinter-приложение сохранено: practice_data\student_gui.py
Файл зависимостей сохранен: practice_data\requirements.txt

**Запуск приложения с графическим интерфейсом.**

После сохранения файла приложение запускается из терминала командой:

"""bash
python practice_data/student_gui.py
"""

Если команда "python" недоступна, можно использовать "python3" или "py".
Перед запуском установите зависимости:

"""bash
python -m pip install -r practice_data/requirements.txt
"""

В окне приложения можно выбрать или создать Parquet-файл, добавить
студента, сохранить данные, загрузить данные, проверить структуру
Parquet-файла, вывести всех студентов, вывести студентов со средним
баллом выше 4.0 и удалить строки по выбранной колонке.